### ISSUE TITLE
Stats extension is broken

### ISSUE THREAD

**Issue by spacegears** [tormater/tormater-forum#12]
Okay, so I've noticed that the stats in the footer section of my forum wasn't working properly, the numbers are off.

If you look up "show table status wrong row count" or something similar, you'll find plenty of threads for this issue, like this one for example: [https://github.com/HeidiSQL/HeidiSQL/issues/1108#issuecomment-664845235](https://github.com/HeidiSQL/HeidiSQL/issues/1108#issuecomment-664845235)

Executing `ANALYZE TABLE` did update the numbers but that's just temporary.

At first I thought it was something on my end, but no: if you take a look at the number of threads in the categories section of the official Tormater forum and then compare it to the stats in the footer, it's clearly not right.

**Comment by tormater-yak** [comment]
Fixed.
