### ISSUE TITLE
Translation needed for the new ip user deletion button

### ISSUE THREAD

**Issue by tormater-yak** [tormater/tormater-forum#15]
There are two new language strings for a new feature I have just added:
`240    "panel.DeleteAllUsersOnIP" => "Delete all users that share this IP address",`
`241    "panel.DeleteAllIPSuccess" => "Successfully deleted all users on this IP address.",`

@cosmopolityan @abdulhalim 
I've added the strings temporarily in English to the Russian and Persian language packs, so it should be easy to find them in the files.

Thanks in advance!

**Comment by abdulhalim** [comment]
240 "panel.DeleteAllUsersOnIP" => "حذف تمام کاربرانی که این آدرس آی پی را به اشتراک دارند",
241 "panel.DeleteAllIPSuccess" => "با موفقیت تمام کاربرانی که با این آدرس آی پی حذف شدند.",

**Comment by tormater-yak** [comment]
> 240 "panel.DeleteAllUsersOnIP" => "حذف تمام کاربرانی که این آدرس آی پی را به اشتراک دارند",
> 241 "panel.DeleteAllIPSuccess" => "با موفقیت تمام کاربرانی که با این آدرس آی پی حذف شدند.",

Added! Thanks so much!
