### ISSUE TITLE
Online demo and details about tormater

### ISSUE THREAD

**Issue by pwFoo** [tormater/tormater-forum#2]
Hi @tormater-yak 
You invited me to organisation?

Do you have some more information about tormater-forum? Planned features (desktop, notifications? api driven? extendable? installable web pwa? ...).

I like software with flexibility by extensions / plugins (hook into core methods and extend with plugins) and separation of html, css / design and api calls to fill the templates.

**Comment by tormater-yak** [comment]
> Do you have some more information about tormater-forum? Planned features (desktop, notifications? api driven? extendable? installable web pwa? ...).

Yeah, I'm planning on adding desktop notifications but currently I have no HTTPS environment to test them in. I'm also going to add extensions to the software (I haven't gotten around to it yet). As of right now, I'm working on more basic functionality of the software.
