### ISSUE TITLE
"Midnight" theme is unpolished and rough

### ISSUE THREAD

**Issue by alfred-don** [tormater/tormater-forum#3]
I noticed that Midnight isn't nearly as polished or pretty as Skyline, and you haven't updated Midnight since it was added.
I'm wondering if Midnight will be improved or if this is it's final look?

**Comment by tormater-yak** [comment]
> I noticed that Midnight isn't nearly as polished or pretty as Skyline, and you haven't updated Midnight since it was added. I'm wondering if Midnight will be improved or if this is it's final look?

I will work on the skin in the future, it was mainly added as a way for me to test multi-skin compatibility.

**Comment by tormater-yak** [comment]
I've deleted the skin since I don't think anyone ever used it or ever will.
