### ISSUE TITLE
Sections

### ISSUE THREAD

**Issue by Leviaria** [tormater/tormater-forum#7]
If you go into the section itself it wont show the Threads inside.

(In the official support forum it works).

**Comment by GigaHacer** [comment]
> If you go into the section itself it wont show the Threads inside.
> 
> (In the official support forum it works).

What do you mean by the section? I think posting screenshots of the issue for clarification would be useful.

**Comment by Leviaria** [comment]
Sorry, I was a bit pressed for time when I wrote the comment.

![Alt Text](https://i.imgur.com/qgQzebN.gif)

**Comment by Leviaria** [comment]
> > If you go into the section itself it wont show the Threads inside.
> > (In the official support forum it works).
> 
> What do you mean by the section? I think posting screenshots of the issue for clarification would be useful.

Sorry, I was a bit pressed for time when I wrote the comment.

![Alt Text](https://i.imgur.com/qgQzebN.gif)

**Comment by tormater-yak** [comment]
> > > If you go into the section itself it wont show the Threads inside.
> > > (In the official support forum it works).
> > 
> > 
> > What do you mean by the section? I think posting screenshots of the issue for clarification would be useful.
> 
> Sorry, I was a bit pressed for time when I wrote the comment.
> 
> ![Alt Text](https://camo.githubusercontent.com/e6ae6b5234435dc630bb1dcda2a59dd1c424b404471b2d0ec865a6ead8b7f3d4/68747470733a2f2f692e696d6775722e636f6d2f7167517a65624e2e676966) [ ![Alt Text](https://camo.githubusercontent.com/e6ae6b5234435dc630bb1dcda2a59dd1c424b404471b2d0ec865a6ead8b7f3d4/68747470733a2f2f692e696d6775722e636f6d2f7167517a65624e2e676966) ](https://camo.githubusercontent.com/e6ae6b5234435dc630bb1dcda2a59dd1c424b404471b2d0ec865a6ead8b7f3d4/68747470733a2f2f692e696d6775722e636f6d2f7167517a65624e2e676966) [ ](https://camo.githubusercontent.com/e6ae6b5234435dc630bb1dcda2a59dd1c424b404471b2d0ec865a6ead8b7f3d4/68747470733a2f2f692e696d6775722e636f6d2f7167517a65624e2e676966)

This is odd--I can't reproduce this at all on my end. 
Can you turn on error reporting in PHP? Generally errors in the script are the cause for the page just ending like that.

**Comment by Leviaria** [comment]
Yeah, I noticed that the version from the repository differs from the one in the release. 

Nevertheless, the error still persists. Unfortunately, it doesn't seem to be a PHP error since my log file remains empty (I also enabled error_log = php_errors.log and set it to on). The only thing I can provide you with is the console output:

Responded Source Code:
https://pastebin.com/raw/fQiLWnjk

![image](https://github.com/tormater/tormater-forum/assets/113382526/9c8927ae-4850-43ee-82f6-1f45b453917f)
![image](https://github.com/tormater/tormater-forum/assets/113382526/e88a55d6-d60b-4fe4-a7e2-ab4effdf2089)
![image](https://github.com/tormater/tormater-forum/assets/113382526/05a5feff-bb80-4fa9-978a-a489a85c8c30)

**Comment by tormater-yak** [comment]
> Yeah, I noticed that the version from the repository differs from the one in the release.

Well yeah, but not only were you not running the latest repo version, you weren't running the latest release either.
(I can tell this by the fact that the table header colors don't match the main header color, which they do after the forum color update, where you can set your own.)

![image](https://user-images.githubusercontent.com/113382526/243381741-9c8927ae-4850-43ee-82f6-1f45b453917f.png)
500 Internal Server Error indicates a PHP error.

> Nevertheless, the error still persists. Unfortunately, it doesn't seem to be a PHP error since my log file remains empty (I also enabled error_log = php_errors.log and set it to on). The only thing I can provide you with is the console output:

This is the page console, not PHP console output.
Try setting `display_errors = On` in your config, then screen-shot the page.

Also, does this occur in any other pages other than this one?

**Comment by Leviaria** [comment]
I switched from PHP 7.4.0 to 8.1.18 and it seems to have fixed my problem, even with my custom CSS. I reconstructed the whole thing again and it definitely seems to be a version issue for me. 

(Issue closed from my side)

![image](https://github.com/tormater/tormater-forum/assets/113382526/6541f8f7-7946-43c4-b838-c9c582603501)

Thanks! :)

**Comment by Leviaria** [comment]
Found the Issue:

Fatal error: Uncaught mysqli_sql_exception: Unknown column 'timestamp' in 'order clause' in E:\xampp\htdocs\pages\category.page.php:40 Stack trace: #0 E:\xampp\htdocs\pages\category.page.php(40): mysqli->query('SELECT * FROM t...') #1 E:\xampp\htdocs\index.php(117): require('E:\\xampp\\htdocs...') #2 {main} thrown in E:\xampp\htdocs\pages\category.page.php on line 40

**Comment by tormater-yak** [comment]
> Found the Issue:
> 
> Fatal error: Uncaught mysqli_sql_exception: Unknown column 'timestamp' in 'order clause' in E:\xampp\htdocs\pages\category.page.php:40 Stack trace: #0 E:\xampp\htdocs\pages\category.page.php(40): mysqli->query('SELECT * FROM t...') #1 E:\xampp\htdocs\index.php(117): require('E:\xampp\htdocs...') #2 {main} thrown in E:\xampp\htdocs\pages\category.page.php on line 40

This is bizzare. I'll have to set up a testing installation on 7.4.8 later.
